export const events = [
  {
    slug: "pokemon-go-community-day",
    image: "/images/pokemon-go-community-day.jpg",
    title: "Pokemon GO Community Day Fest",
    location: "Lima, Peru",
    date: "April 13, 2026",
    time: "2:00 PM - 6:00 PM",
  },
  {
    slug: "kanto-trainer-cup",
    image: "/images/kanto-trainer-cup.jpg",
    title: "Kanto Trainer Cup",
    location: "Mexico City, Mexico",
    date: "May 2, 2026",
    time: "10:00 AM - 7:00 PM",
  },
  {
    slug: "eevee-evolution-expo",
    image: "/images/eevee-evolution-expo.webp",
    title: "Eevee Evolution Expo",
    location: "Santiago, Chile",
    date: "May 18, 2026",
    time: "11:00 AM - 8:00 PM",
  },
  {
    slug: "pokemon-card-battle-weekend",
    image: "/images/pokemon-card-battle-weekend.jpg",
    title: "Pokemon Card Battle Weekend",
    location: "Bogota, Colombia",
    date: "June 6-7, 2026",
    time: "2 Days",
  },
  {
    slug: "johto-legends-meetup",
    image: "/images/johto-legends-meetup.webp",
    title: "Johto Legends Meetup",
    location: "Cusco, Peru",
    date: "June 20, 2026",
    time: "5:00 PM - 9:00 PM",
  },
  {
    slug: "pikachu-fan-festival",
    image: "/images/pikachu-fan-festival.jpg",
    title: "Pikachu Fan Festival",
    location: "Buenos Aires, Argentina",
    date: "July 11, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "hoenn-adventure-camp",
    image: "/images/hoenn-adventure-camp.jpg",
    title: "Hoenn Adventure Camp",
    location: "Quito, Ecuador",
    date: "August 1, 2026",
    time: "8:00 AM - 4:00 PM",
  },
  {
    slug: "sinnoh-strategy-summit",
    image: "/images/sinnoh-strategy-summit.webp",
    title: "Sinnoh Strategy Summit",
    location: "Monterrey, Mexico",
    date: "August 22, 2026",
    time: "10:00 AM - 5:30 PM",
  },
  {
    slug: "gym-leaders-showdown",
    image: "/images/gym-leaders-showdown.avif",
    title: "Gym Leaders Showdown",
    location: "Sao Paulo, Brazil",
    date: "September 12, 2026",
    time: "1:00 PM - 9:00 PM",
  },
  {
    slug: "pokemon-cosplay-carnival",
    image: "/images/pokemon-cosplay-carnival.jpg",
    title: "Pokemon Cosplay Carnival",
    location: "La Paz, Bolivia",
    date: "October 3, 2026",
    time: "12:00 PM - 8:00 PM",
  },
  {
    slug: "unova-trading-night",
    image: "/images/unova-trading-night.jpg",
    title: "Unova Trading Night",
    location: "Medellin, Colombia",
    date: "October 24, 2026",
    time: "6:00 PM - 10:00 PM",
  },
  {
    slug: "master-ball-grand-finals",
    image: "/images/master-ball-grand-finals.avif",
    title: "Master Ball Grand Finals",
    location: "Madrid, Spain",
    date: "November 14, 2026",
    time: "9:00 AM - 7:00 PM",
  },
];
